[theme]
base="light"
primaryColor="#fd3131"
backgroundColor="#f5fafa"
secondaryBackgroundColor="#d3dcdc"



[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[ui]
browser.gatherUsageStats = false
