[theme]
base="light"
primaryColor="#fd3131"
backgroundColor="#c9c7c7"
secondaryBackgroundColor="#8dc37b"


[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[ui]
browser.gatherUsageStats = false
