[theme]
base="light"
primaryColor="#fd3131"
backgroundColor="#ececec"
secondaryBackgroundColor="#cedcf7"


[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[ui]
browser.gatherUsageStats = false
