[theme]
base="light"
primaryColor="#fd3131"
backgroundColor="#e1e8e8"
secondaryBackgroundColor="#8dc37b"


[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[ui]
browser.gatherUsageStats = false
